name: Build & Publish

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: 🐳 Build
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🔑 Docker Registry Auth
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: 🐳 Docker build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/portal-web:latest
          build-args: |
            COMMIT_SHA=${{ github.sha }}
